name: CI workflow

on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container: 
      image: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

      - name: Check documentation coverage
        run: |
          # Assuming you're using Sphinx for documentation
          pip install sphinx
          sphinx-build -b html docs/ docs/_build
          # Calculate documentation coverage
          python calculate_documentation_coverage.py

      - name: Analyze code security
        run: |
          # Assuming you're using Bandit for code security analysis
          pip install bandit
          bandit -r src

      - name: Static code analysis
        run: |
          # Assuming you're using Pylint for static code analysis
          pip install pylint
          pylint src
